import("../../../webrtc.gni")

rtc_library("l4s_network_controller") {
  sources = [
    "l4s_bandwidth_fusion.cc",
    "l4s_metrics_collector.cc",
    "l4s_network_controller.h",
    "l4s_network_controller.cc",
  ]
  
  deps = [
    "//api:field_trials_view",
    "//api/numerics:numerics",
    "//api/environment",
    "//api/rtc_event_log",
    "//api/test/metrics:global_metrics_logger_and_exporter",
    "//api/test/metrics:metrics_logger",
    "//api/transport:bandwidth_usage",
    "//api/transport:goog_cc",
    "//api/transport:network_control",
    "//api/units:data_rate",
    "//api/units:data_size",
    "//api/units:time_delta",
    "//api/units:timestamp",
    "//logging:rtc_event_log_api",
    "//rtc_base:checks",
    "//rtc_base:logging",
    "//rtc_base/experiments:field_trial_parser",
    "//system_wrappers",
    "//modules/rtp_rtcp:rtp_rtcp_format",
    "//modules/pacing:pacing",
    "//modules/congestion_controller/goog_cc:goog_cc",
    "//modules/congestion_controller/goog_cc:estimators",
    "//modules/congestion_controller/goog_cc:delay_based_bwe",
    "//modules/congestion_controller/goog_cc:send_side_bwe",
    "//modules/congestion_controller/goog_cc:probe_controller",
    "//third_party/abseil-cpp/absl/strings",
  ]
}

